### ISSUE TITLE
Blank page in IE11 after the javascript exception

### ISSUE THREAD

**Issue by tolbxela** [opensupports/opensupports#110]
![image](https://user-images.githubusercontent.com/4910589/33336762-335dc20a-d471-11e7-81b9-18c1d17f3fe9.png)

```
Object doesn't support property or method 'startsWith'
main.js (13,15991)
```

![image](https://user-images.githubusercontent.com/4910589/33336437-2f1af8c6-d470-11e7-97f0-27aab693658b.png)

![image](https://user-images.githubusercontent.com/4910589/33336721-1894c95a-d471-11e7-8bd7-676e9e136ecf.png)

The error occurs in both **/support** and **/support/admin** sites.

**Comment by Paul2301** [comment]
thanks Ivan

**Comment by ivandiazwm** [comment]
UPDATE: The problem is that IE 11 doesn't support some methods like `startsWith`, `includes` and `find`. The issues come primarily by our rich text dependency.
I manage to fix this issue, but there are others while you navigate.

We need to add some polyfills in order to support IE11 (maybe use lodash functions) and remove the use a regular `textarea` instead of rich text editor in this case.
