### ISSUE TITLE
Feature suggestion - custom tags

### ISSUE THREAD

**Issue by nickbe** [opensupports/opensupports#146]
I'd like to suggest that managers are allowed to create custom tags which can latter be assigned to tickets by staff members.

This would be a great way to be able to filter tickets without over complicating things.
Tags could be used to represent tickets status as well as different projects or technical terms....

**Comment by nickbe** [comment]
Are custom tags considered?

**Comment by ivandiazwm** [comment]
Yes, this is a feature that should be added to our list.

**Comment by nickbe** [comment]
Excellent! In my opinion one of the most useful funtions when you think about it

**Comment by ivandiazwm** [comment]
@nickbe @mredigonda @guillegiu I've some ideas for the design of custom tags. Please let me know what do you think.

1) We will first need a new tab for managing custom tag, it should look like this:
![custom_tags1](https://user-images.githubusercontent.com/6447076/47037948-a034af00-d156-11e8-8a41-032ec7fa198e.jpg)

2) We can use the component `ColorPicker` (like Topic form) supporting add/edit a tag
![custom_tags2](https://user-images.githubusercontent.com/6447076/47037947-a034af00-d156-11e8-8de9-42557d9a304f.jpg)
![custom_tags3](https://user-images.githubusercontent.com/6447076/47037946-a034af00-d156-11e8-975c-c661d9bff3be.png)

4) Regarding presentation, we could have it in a second line under the title
![custom_tags4](https://user-images.githubusercontent.com/6447076/47037945-9f9c1880-d156-11e8-8335-2ad6d20fc3fe.png)

5) Or it may be better to have it the same line and move to a new line if it overflows.
![custom_tags5](https://user-images.githubusercontent.com/6447076/47037944-9f9c1880-d156-11e8-9ff7-66544de3f5cd.png)
![custom_tags6](https://user-images.githubusercontent.com/6447076/47037943-9f9c1880-d156-11e8-8218-28d3c255fbd4.png)

6) An alternative could be to put inside the tooltip to avoid style breaking.
![custom_tags7](https://user-images.githubusercontent.com/6447076/47037941-9f038200-d156-11e8-91a8-482cb4809187.png)

7) We will also need to add a field in the ticket view header and in the ticket list filter.
![custom_tags8](https://user-images.githubusercontent.com/6447076/47037940-9f038200-d156-11e8-8584-5cd26ca86cfb.png)

I'm thinking we could make something similar to the Semantic-UI multiple selector:
https://semantic-ui.com/modules/dropdown.html#multiple-selection
The component could be `DropDownMultiple` or something similar.

8) If we want to avoid to create this component because we feel it could take a lot, we may just add checkboxes with the tags.

**Comment by nickbe** [comment]
Hi Ivan,

first - thanks for all this effort. Excellent drafts and ideas 😄 

The semantic selection (https://semantic-ui.com/modules/dropdown.html#multiple-selection) looks great and I cannot imagine a better way for multiple tag selection. It's defintely something worth implementing for this task.

The ticket line: In this example the ticket title is only one word, but taking a look at our real world titles they are at least one line, two most of the time. I'd try to take no.3 - but I think the best way is to show the tags ABOVE the title line(s) and not below. Maybe you could give this a shot.

I have nothing to add to the custom tag editor. Simple and effective. Great thing!

As for the popup: I would rather try to avoid it completely. The open/closed status should be in the list. The same goes for the owned flag - although I would replace it with a simple icon, together with the comments counter - just use a simple bubble counter in the list.
Finally the priority: I would replace it with the custom tags completely. Same effect and the tags filter would definetely suffice.

Thanks Ivan. OpenSupports is definetely is going to be fine!

**Comment by versavius** [comment]
Yes this would be a very powerful feature, something to consider is with tickets having tags you can do all sorts of reporting based on tags.

You could even later on create automatic rules to auto tag tickets based on certain criteria, but that is something for another day, just a thought for after this gets added

**Comment by nickbe** [comment]
I think it's definetely too complicated to maintain and handle. OpenSupports should be installed / configured within a minute.

**Comment by versavius** [comment]
> I think it's definetely too complicated to maintain and handle. OpenSupports should be installed / configured within a minute.

Do you mean tags or rules ? If you mean rules then yes i agree that can get quite complex

**Comment by nickbe** [comment]
Rules :)
