### ISSUE TITLE
'Organisation' field needed for ticket creation

### ISSUE THREAD

**Issue by nickbe** [opensupports/opensupports#307]
Especially when I create a user myself in future versions, I'd really need a field "Organisation".
In our case the system is used for multi client purposes.

**Comment by nickbe** [comment]
@ivandiazwm - What do you think Ivan? Is this reasonable? I guess it's only a minor addition anyway.

**Comment by versavius** [comment]
What if under users you had an organisations option, so you could create a whole list of organisations.

Then you can assign each user to that organisation.

This way when a registered user logs a ticket it will automatically be tagged with the correct organisation.

Also this would allow reporting on tickets by organisation?

**Comment by nickbe** [comment]
I would simply solvel this with a simple Textfield. But maybe the whitelist filter could solve this automatically if you simply  show the domain name of the user in the tickets :)

**Comment by versavius** [comment]
Showing the domain name would work if the client only uses one domain name or if the domain name is meaningful, i would prefer to add a list of companies and then assign users to companies so that the organisation field is properly populated with the users organisation.

This way you have the data in the database correctly and you can pull it out for reporting and analysis.

(The reporting and analysis would be done separate of this project as that would be out of scope, but you get the idea)

**Comment by nickbe** [comment]
This issue seems to be solved in the latest 4.4 Release.
