### ISSUE TITLE
ATTENTION hacker attack

### ISSUE THREAD

**Issue by carlopilurzi** [opensupports/opensupports#321]
Attention, Friday 27 our site was attacked by a group of hackers that through the registration as a user has opened a ticket with an executable that has deleted all the db opensupport, adding a page of their creation instead of the opensupport page see attachments
[hacker.pdf](https://github.com/opensupports/opensupports/files/2438047/hacker.pdf)
[Hacked By Cyber-Turks.pdf](https://github.com/opensupports/opensupports/files/2438048/Hacked.By.Cyber-Turks.pdf)

**Comment by nickbe** [comment]
Oops. This would be a serious security breach.
@ivandiazwm - Could you please look into this asap.
@carlopilurzi - Can you provide the hacked sources for Ivan?

**Comment by carlopilurzi** [comment]
Hi, they uploaded a file as an attachment that replaced the files in the root directory. I can not tell you anything else I hope I've been useful

**Comment by ivandiazwm** [comment]
I've found the cause of it. I'm working on a solution.

**Comment by ivandiazwm** [comment]
@carlopilurzi @nickbe The issue seems to be that you can upload php/image executable files and access them through the browser. I've temporary avoided this by adding an `.htaccess` with `Deny from all` to ensure they can only be accessed by the `/system/download` path.

If you extract the following `zip` on your OpenSupports' directory, it should work. It only contains the `.htaccess` for `api/files/` folder.
[opensupports_update_4.2.0_hotfix.zip](https://github.com/opensupports/opensupports/files/2439227/opensupports_update_4.2.0_hotfix.zip)

Also change permissions of files folder to `chmod 700 api/files/` (this is not required, but adds an extra layer).

That should temporary solve it. I will release a temporary hotfix release for the current version.
For the next release I'll implement a better file uploading library to make sure we don't have this kind of problems in the future.
