### ISSUE TITLE
Articles should also be optionally 'private'

### ISSUE THREAD

**Issue by nickbe** [opensupports/opensupports#331]
It should be possible to differ between 'public' articles and 'internal' articles.
A simple switch 'internal only' would do when creating an article.

**Comment by guillegiu** [comment]
Hi Nick im working on this feature and i think it would be better if we create "Private topic" with its own private articles instead  directly create "private articles". I think it will be more consistent in this way because it can be confusing having private and public articles mixed.Tell me if you agree

**Comment by nickbe** [comment]
This is the logical solution of course and you're right there.

**Comment by nickbe** [comment]
Can you let us choose the departments for which topics are valid (privates only)? 

Depending on the staffs department this would also make sense regarding who may care about which topics.

**Comment by ivandiazwm** [comment]
This feature has been released
