### ISSUE TITLE
Assign ticket to department

### ISSUE THREAD

**Issue by nickbe** [opensupports/opensupports#359]
As a result of todays work I suggest we add an additional item to the Assign dropdown box: "Assign to department" We had the staff members of the whole department responsible for solving some problem.

**Comment by ivandiazwm** [comment]
I don't see what is the issue here. Currently, if a ticket is assigned to a department it will be shown to all staff members of that department. A staff will only see the unassigned tickets of its departments in "New Tickets" and the assign dropdown only shows staff members who have that department assigned.

**Comment by nickbe** [comment]
Ok, but then there must be a bug. Because when I create a ticket and then assign it to myself, the I‘m definetely the only one who can see it. Ticket was in department „Tech Support“, but no one fron Techsupport can see the ticket except me

**Comment by nickbe** [comment]
Could you locate this problem?

**Comment by nickbe** [comment]
@ivandiazwm Have you looked into the problem that I can see tickets in my department, but not write or answer comments as long as I'm not assigned to the ticket?

**Comment by nickbe** [comment]
Closed. Would automatically be solved by #412
