### ISSUE TITLE
How to change email sender title

### ISSUE THREAD

**Issue by johnshumon** [opensupports/opensupports#361]
When a new ticket is created an email is sent to the email creator. Received email has **OpenSupports** as sender title. How do I change it to custom one for example my name? This is how received email looks like when a new ticket is created:
![screen shot 2018-10-22 at 12 55 53 pm](https://user-images.githubusercontent.com/5329878/47287131-e035df00-d5f9-11e8-8839-5d6e797a8437.png)

I have checked both system preferences and advanced settings. Couldn't find anything. My guess was auto generated email would take **Support center title** value as email sender title but it didn't. My current settings as follows:
![screen shot 2018-10-22 at 12 58 13 pm](https://user-images.githubusercontent.com/5329878/47287404-ccd74380-d5fa-11e8-8d20-3ef17f0d8459.png)

**Comment by johnshumon** [comment]
Solution
```
/api/libs/MailSender.php --> line 28
$this->mailOptions['fromName'] = 'OpenSupports';
```

**Comment by mredigonda** [comment]
Thanks for sharing this here, it will be useful for anyone looking to do the same in the future.

In my opinion, your first guess was correct, we really **should** be using the **Support Center Title** field here.

I'll close this issue so that it is searchable, but I'll be creating a new one to handle the change to use the Support Center Title as the email sender.
