### ISSUE TITLE
Change user password

### ISSUE THREAD

**Issue by Mte90** [opensupports/opensupports#363]
Seems that in the interface there is no field that enable to change the user password.

As admin I should be able to do that, I will try from the database anyway but this is not a good solution right now.

**Comment by nickbe** [comment]
Users are meant as "external" users, like clients or other third parties. As a user you can click on the "I forgot my password" button to reset the password. This is a well established method and you should not be able to interfere with the user passwords yourelf.

**Comment by Mte90** [comment]
And I have an user cases that confirm the need of that feature:  
An user that recovered the password and changed but cannot access, so asked me to change the password and try it. So I changed by DB, tested and got the access, so the customer done more tests.

**Comment by nickbe** [comment]
From an administrators point of view being able to change the access or directly access/simulate access to a user account without his consent is questionable in many ways. (in so far as the user is not part of the company - and even this could be tricky sometimes). 

So as a member of the european privacy protection act, I have to be completely against such a feature, because it would render the software unusable for us.

**Comment by Mte90** [comment]
I am european too but how I can handle this request from an UE user?

**Comment by nickbe** [comment]
Simply advise users to enter their mail adress and click on the "Forgot your password" button:

![image](https://user-images.githubusercontent.com/10890765/47554788-74f65080-d90a-11e8-8d11-f22c1bdb1151.png)

That way the administrator has no access to the password and the user is able to reset his or her password any time they want.

**Comment by Mte90** [comment]
Well my user already done that step and he was complaining of no access to the portal after recovering. So I cannot test for him that and he asked me to change his password, changed and tested with a login.
Without that feature of changing the password as admin for me was impossible to resolve the problem and test it.
IT is one of the usual procedure that when you have problem on accessing you reach the admin that change it for you.

**Comment by nickbe** [comment]
I've just tested the password recovery function and it seems to work as expected for me. 

Is this a problem with his initial access to the account? (Did he receive the confirmation mail request?) or did he forget his password after he was already logged in?

**Comment by Mte90** [comment]
I don't know but for newbie users or non-techie people is good to know that the admin done that test and saw that was working.

**Comment by nickbe** [comment]
@ivandiazwm Could you check what happens if you don't confirm a new user, and instead try to immendiately request "I forgot my password". I didn't receive a mail when I did this. So maybe this is the problem - You register yourself as a new user, but instead of responding to the conformation mail you just press the "forgot" link.

**Comment by ivandiazwm** [comment]
I was able to recover the password while it was not even verified, it seems it's working correctly.
@Mte90 Please make sure the user has its account verified. It should show a warning on its profile if it's not.
![screenshot](https://user-images.githubusercontent.com/6447076/47578320-79793400-d91f-11e8-809c-7faec0923626.png)
You can manually verify an user on the database by changing the `verification_token` row on `ticket` table to `NULL`.
If the email is not verified, the user will not be able to log in and a message `Email is not verified` will appear. I'm thinking we should maybe add a "resend verification email" button like other websites do, because currently it's only sent once.

Even if we're talking about users without expertise. Email verification it's still necessary because we need to very the authenticity of the email, of course this won't be always needed when we implement #207.

**Comment by nickbe** [comment]
Since we talk about it. Wouldn't it be better if new users would just receive a mail and can then also choose their own password? (I'm not talking about stuff though)

**Comment by Mte90** [comment]
and again I need to change the password for an user that has problems on access the website to check what is happening.

**Comment by Mte90** [comment]
Just for who is wondering what is the hash to do that change from the db is bcrypt.

**Comment by mredigonda** [comment]
The use case provided is not really supporting implementing this feature, but instead, pointing out that there may be a problem with the "forgot my password" functionality.

As @nickbe pointed out, I don't think Opensupports should easily allow admins to change user passwords, the admin will be able to do it anyways, but Opensupports shouldn't encourage it.

The real fix to this issue is to make sure that the "forgot my password" functionality works as expected, so I will be closing this issue, but any issue related to the password recovery system not working will be more than welcome.

**Comment by salimzadeh** [comment]
Why can't Admin change the  user's password?
