### ISSUE TITLE
Public Tickets

### ISSUE THREAD

**Issue by SunnyTeater** [opensupports/opensupports#364]
I don't think I saw this request here.

What about public tickets?
In my opinion it is helpful if you have a lit of customers with the same issue and you don't want a flood of tickets about one problem.
Example: One program in you're company is not working and a lot of users on multiple locations has the same issue but they will not talk with each other. 

So it would be easier if you could just say "public ticket" so everyone can see this problem if they wants to wrote a familiar issue.   

Or maybe you could just implement a broadcast message that shows up when u wnat to create a ticket.

**Comment by nickbe** [comment]
OpenSupports already has it's articles. If there's some public knowledge it should be compiled into an article. Otherwise a real tickets with its responses might contain names and other personal stuff not intended for public eyes. This could easily be a legal problem as well.

In my own company we use articles like a small knowledgebase or FAQ. In my opinion it doesn't make sense to let users browse through the communication of a ticket. Knowledge must be presented in a short and understandable way. And issue tickets are not created to provide knowledge, but to seek knowledge and are thus not fitted for the publiv.

**Comment by SunnyTeater** [comment]
So you also use articles to say to you're customers like: "Hey Guys, don't create a ticket, we know the server is down. We expect downtime of 30min." 

And I thought it would be helpful if you can see, hey somebody already created a ticket. Let's open it and see if we get newer informations.

It shouldn't be knowledge that u need a lot, just for a moment like my example above.

After you're feedback, i think a "broadcast" - message would help more than view public tickets.

**Comment by nickbe** [comment]
If the server's down and it's on purpose then there's a simple maintenance switch for this:

![image](https://user-images.githubusercontent.com/10890765/47555658-abcd6600-d90c-11e8-8a2e-469179d8de76.png)

Actively telling the users (in our case clients) that you have an issue with your issue ticket system is probably not a good idea anyway. Makes you look like a fool, doesn't it. 

If you need to search for already existing ticket on the same subject then I'd recommend a much more complex system like github itself. (At least for software development). Here this works because everyone accepts that their posts can be viewed by anyone else.

But in support ticket systems like OpenSupports privacy is a major concern and it's important that external users know their tickets are kept private. Otherwise you would have to ask users if they want their ticket to be public, which I can promise you will not work at all.

**Comment by nickbe** [comment]
Ah now I get it. What you mean is some sort of public dashboard for common anouncements like on a status page. "Mailserver 003 is currently down for maintenance. Estimated time 2 hours" or something like that.

Sorry I didn't get you initial thoughts here. Well that's indeed a really interesting thought.
We would need to post a ticket internally with a special flag like "[x] Public Announcement" set. Then the "announcement" would simply be visible to users as long as the ticket itself is visible. 
An additional switch in the settings would be needed where the administrator can determine if announcements are visible before or after the user logs in.

@ivandiazwm Interesting?

**Comment by ivandiazwm** [comment]
We have received a similar feature request from email, requiring a notification system (sort like public announcements) for staff members.
This makes sense to me and it'll be very helpful. However I wouldn't use tickets for this, just a message.
I have created a new issue #366 where the feature can be discussed.
