### ISSUE TITLE
How to download all the tickets from ticket section

### ISSUE THREAD

**Issue by sunilpatro08** [opensupports/opensupports#387]
Hi Team,

Could you help me to customize the download button below the table where shows all the tickets under ticket sections with download option as pdf / excel.

Thanks

**Comment by SunnyTeater** [comment]
Do you only want to download the list? Or every ticket with content?

I would agree, a possibilitie to export some statistic information to excel could be useful to analyze the data.
Does it seem possible @ivandiazwm  ?

**Comment by SunnyTeater** [comment]
@nickbe yes that is possible, but it is very awkward. But only changing the date format in excel is a horror. 
Maybe you want to show how long a ticket is open in a department (average). 
Or something else..

**Comment by nickbe** [comment]
That depends on your knowledge of SQL itself. To me breaking long SQL queries apart and splitting them into parameter like structures for frameworks is much more awkward than writing a big and nice nested query which gives me exactly the results I want. 😁

**Comment by SunnyTeater** [comment]
@nickbe my SQL skills ... i would say i have no skills there :D

im just a normal ITler with some linux experience , not a programmer :p

**Comment by ivandiazwm** [comment]
I don't think it's optimal to use SQL for this, since we are using an `ORM` (RedBean) and it would require internal knowledge the tool.
I'd recommend to make a request to `/ticket/get` because the response json contains all the data you need for a ticket. You use integrate a xls/pdf generator on frontend to create the file (like [exceljs](https://www.npmjs.com/package/exceljs) or [pdfmake](https://www.npmjs.com/package/pdfmake)).
