### ISSUE TITLE
template issues 4.3.1

### ISSUE THREAD

**Issue by SunnyTeater** [opensupports/opensupports#388]
Hey Guys,

since version 4.3.1 i have some issues by saving email-templates and custom responses

Email Templaes:
- if i want to save a template i need to klick twice on "save" 
- if u have only one language active u also need to set the language even when it shows as active.

custom responses:
- if u want to switch between answers u always becomes the message that u should save or changes will get lost
- if u are the firt time there, every field is empty. So i thougt that u can enter a new costom respons and klick save. But first u need to klick "Add new" and than u can enter your respons and than u can klick "save" 
Can we improve that? - hope its unterstandable.

**Comment by ivandiazwm** [comment]
Hi @SunnyTeater , thanks for reporting this issues

> Email Templaes:
> 
> if i want to save a template i need to klick twice on "save"

The problem with this is that retrieving the mail templates takes too long and it's not in sync with the loader. If you wait more seconds instead of doing a second click, it will change.
I've done a refactor of the mail templates since we have had many issues with it. This issue won't happen aging, the fix will be released in the next version.

> if u have only one language active u also need to set the language even when it shows as active.

Yes, thanks for seeing this, I've fixed it along with the refactor.

> custom responses:
> 
> if u want to switch between answers u always becomes the message that u should save or changes will get lost

This is because the text editor triggers automatic changes when rendered. I've added a better check for it. Now it should not happen unless you click on the form.

> if u are the firt time there, every field is empty. So i thougt that u can enter a new costom respons and klick save. But first u need to klick "Add new" and than u can enter your respons and than u can klick "save"

You're correct. I've fixed it. Now it won't show the form unless you have selected one of the options or "add new".

Thanks aging for reporting them. Once the fixes are merged, they will be available on next release `v4.4.0` and all these issues should be fixed.
