### ISSUE TITLE
Password recover redirects to /admin 

### ISSUE THREAD

**Issue by comdagworld** [opensupports/opensupports#394]
Sorry in german...
Wenn ein Benutzer das Passwort erneuert hat, kommt danach die Admin-Anmeldungsseite und nicht die normale Startseite.

**Comment by nickbe** [comment]
Let me translate this
@ivandiazwm - It seems that after a user has changes the password he's rerouted to the admin login rather than the standard user login page.

**Comment by ivandiazwm** [comment]
@nickbe Yes, this should be fixed for the next release, with this commit:
https://github.com/opensupports/opensupports/commit/9a40c63cf4a347d77a057ecad8be03cc8268ed42

**Comment by nickbe** [comment]
@comdagworld - Sieht so aus als ob der Bug bereits gefixt wurde. Im nächsten Release sollte es bereits behoben sein. Ich denke Du kannst das Ticket soweit wieder schließen.

**Comment by comdag** [comment]
Can you please tell me what I have to change where.
I do not want to re-install the whole system because I've already made too many changes.
I can not find the call in the PHP pages.
Translated by Google

**Comment by comdag** [comment]
Can you please tell me what I have to change where.
I do not want to re-install the whole system because I've already made too many changes.
I can not find the call / function in the PHP pages.
Translated by Google

**Comment by nickbe** [comment]
I think this is a question for @ivandiazwm

**Comment by ivandiazwm** [comment]
@comdag Every time we release a new version, an [upgrade package](https://github.com/opensupports/opensupports/wiki/How-to-Upgrade) is also released for existing installations wishing to upgrade. When the next version is out, you should be able to upgrade it by following our guide without losing any existent data. 

If you have, however, made changes to source code of OpenSupports I would not recommend upgrading because you will lose your code changes.

You can do two things in this case:
1. Clone the repository for [v4.3.1](https://github.com/opensupports/opensupports/tree/v4.3.1)
2. Follow `README.md` instructions and run the dev environment
3. To make frontend changes, edit the files you want in `client/` and the run `gulp prod --api` to generate the `build/js/main.js` and `build/css/main.css`. Then replace the `main.js` and `main.css` file in your installation with this one.
4. To make backend changes, just change the files you want on `server/` and the replace them inside the `api/` folder on your installation (make sure to never replace `config.php`).

This works but if you still want to get the our newer changes, I'd recommend to create your own git repository with your changes and then merge `opensupports:master` into it when a new release is launched to keep it updated.

For this issue in particular, you don't need to do all this. You only need to add the `1*` to the `main.js` file. Look for `.data.staff?"/admin":"/"` and the add a `1*` like this:

![screenshot 1](https://user-images.githubusercontent.com/6447076/48662872-30705780-ea67-11e8-8d75-a6267cde5932.png)

That will fix the issue but if you want to make more changes in the future, I'd recommend to do the mentioned above.

**Comment by ivandiazwm** [comment]
Fixed and released.
