### ISSUE TITLE
Cannot change profile picture

### ISSUE THREAD

**Issue by hasteroid** [opensupports/opensupports#403]
I've installed opensupports 4.3.1 on a shared hosting and most seems right but i can't upload a profile pic, i'm getting just the defined error message and can't figure out what happen.
I tried to edit the validator but seems not to take effect. Tried with own script to upload pics on files/, works fine.

I've tried to get documentation to see installation requirements but i can't found anything, can you help me to fix this?

Thanks

**EDIT:**
Tried server configuration with PHP 7.2, then PHP 7.0, nothing changes.
Tried chmod -R 755 on installation folder. The issue persist

Getting this error on console:

request /staff/edit 
{staffId: 1, file: File(40145)}
main.js:60 
{status: "fail", message: "LinearCongruentialGenerator: gap must be prime", data: null}
data: null
message: "LinearCongruentialGenerator: gap must be prime"
status: "fail"
__proto__: Object

**Comment by hasteroid** [comment]
**SOLVED**

i changed the value on database for file-gap and ticket-gap to a 6-digit prime number and it's working now.

out of curiosity. i would like to know the reason for using primality test on a static value stored on DB as "validation" to upload files, if you can explain me. Thanks

**Comment by ivandiazwm** [comment]
@hasteroid Many users have been having issues with this, it's very weird since we haven't been able to found the reason why for some users the prime number is not generated correctly.

We use a [Linear Congruential Generator](https://en.wikipedia.org/wiki/Linear_congruential_generator) to generate ticket numbers which calculation parameters will be different for each OpenSupports installation. The properties of that algorithm make number generation without collisions until it covers all the period if you use certain coprime/prime values.

We were using this too for file name generation, that's why it fails to upload the file. However, I've deleted the LCG from file name generation since it's unnecessary, for the next version it won't be used there.
