### ISSUE TITLE
smtp server doesnt work correctly

### ISSUE THREAD

**Issue by goldleewtje** [opensupports/opensupports#453]
hey i can't seem to get the smtp server up and running thru opensupport. i have tried setting the port to 25, 567 and 465 any idea what might fix the idea?

**Comment by nickbe** [comment]
We're currently using a full blown Univention Server for this and it works with port 587, which seems to trigger TLS in the OpenSupports routines automatically, which works for us. But we also had our problems with other configurations. I think there might be a problem with the protocols here because even after allowing port 25 the server refused to accept the requests.

**Comment by goldleewtje** [comment]
yeah i tried that aswell but no luck i tried to login on my own server with the credentials at that worked fine so it has to be an issue with opensupport

**Comment by goldleewtje** [comment]
apperently it was an issue with the firewall it is all fixed now

**Comment by 09xShubham** [comment]
what have you done in firewall to resolve the issue can you brief the steps

**Comment by martinvanlijden** [comment]
im sorry it has been years during my first internship. I dont know what i did to fix the issue
