### ISSUE TITLE
Customfields not showing up

### ISSUE THREAD

**Issue by lyrics1988123** [opensupports/opensupports#598]
My CustomFields are not showing up, how can i change that? we really need that..
i dont have userregistration activated and i think it worked when i enabled it a few months ago or so.. but we dont want to use registration..  please check

thanks

**Comment by mredigonda** [comment]
Hey, we found a problem with custom fields if the name contains any spaces, I would suggest you try to use names without spaces until a fix for that problem is pushed to production.
I would be really glad if you can confirm us if that was your problem, otherwise, there might be another problem we need to take a look at.
Thanks a lot for reporting!
