### ISSUE TITLE
Ambiguous error code

### ISSUE THREAD

**Issue by bilalak** [opensupports/opensupports#610]
The /staff/assign-ticket request does not have a department number parameter. Why is it giving an error of wrong department? 

![image](https://user-images.githubusercontent.com/3749328/63794237-8c59ed80-c8cf-11e9-8621-3b514862bdc5.png)

**Comment by mredigonda** [comment]
Every staff member has a set of departments assigned to him. He will only be able to assign a ticket to himself only if the ticket belongs to a department he is in charge of, otherwise, an INVALID_DEPARTMENT error will be thrown, I hope that clears things out.
I'm closing this issue but don't hesitate to comment again, it is just to keep the log of issues cleaner.
