### ISSUE TITLE
How can I modify the code?

### ISSUE THREAD

**Issue by Curry201** [opensupports/opensupports#647]
Hi, I want to change the original source for my enterprise needs, and I want to know if its possible if only change the bundle.js file, or it´s necessary work in other file?
If it´s necessary change the bundle.js file, its necessary change other file?
Pd. I´m new in this platform and I want to learn about it technologies. Thanks.

**Comment by DiegoGonzales** [comment]
I also want to know these... So we can add some more features

**Comment by mredigonda** [comment]
If you want to add more features you could talk to us about what features you wish to implement and directly apply them to the official OpenSupports project, that would benefit us all.

However, if it is a very local change that you want to do, you have to build OpenSupports on your own (it's not recommended to change the bundle.js file, since that will get changed with every upgrade, and it is not structured in a developer-friendly way).
