### ISSUE TITLE
Add more columns in tickets view

### ISSUE THREAD

**Issue by DiegoGonzales** [opensupports/opensupports#661]
Hello, I'm trying to add one more column on the view of All Tickets from Admin called "state" based on the "closed" column in the ticket table in db... I'm trying by editing blundle.js/key: getTableHeaders but can't please there's any way to do this? Thank you

**Comment by mredigonda** [comment]
Hi Diego,

Modifying the bundle.js is not ideal, and it will be easily broken when you try to upgrade OpenSupports to a newer version. You should instead build the development environment, make the modifications, and then run the routines to deploy it.

If you want to develop a well known feature that is wanted by others here, you might as well try to add it to the official OpenSupports source code here with a PR (pull request), and it would be available in the next release, that would benefit us all.

**Comment by DiegoGonzales** [comment]
That would be great! I want to help the project too. I would like to add the feature but how can I set up a development environment?

**Comment by mredigonda** [comment]
The guide in the README would be the way to go, but yes, now it's a bit outdated, so I'm going to tell you how I get up my development environment.

First of all, OpenSupports is divided into frontend and backend, we can run, test and develop them separately, but since the feature you want to implement probably requires to use both, I'll tell you how to do that. Hopefully this will be useful as a reference for other people who also want to implement features/fix bugs.

First of all, we have only run OpenSupports on Linux right now, more specifically, on Ubuntu 14.04/16.04/18.04, and I recommend 18.04 because it comes with some packages already installed by default that turn out to be useful.

The first step is cloning this repository, which you can do with:
```git clone https://github.com/opensupports/opensupports.git```.

**Backend**
1. Install docker (if you use Ubuntu 18.04, you have it already installed)
2. Go to `opensupports/server`
3. Run `make build` to download the copy of the docker images
4. Run `make run` (or `make stop`, and then `make run`) to start all the images
5. Run `make install`, this sets up the database `development` in one docker image, and runs `composer install` (to install PHP libraries) in another docker image

**Frontend**
1. Install yarn
2. Go to `opensupports/client`
3. Run `yarn install`, to get all javascript dependencies

With all of those installed, the steps to start working are:

**Backend**
1. Go to `opensupports/server`
2. Run `make stop` then `make run`
3. Run `make sh` (this will connect you via SSL one of the docker images)
4. Run `cd /var/www/html/`
5. Run `php -S 127.0.0.1:8080`, this will start the backend server in the port 8080.

**Frontend**
1. Go to `opensupports/client`
2. Run `yarn start`

With all of those steps, you can already start developing, although you will need to go through the installation. We usually run the ruby tests first, since they fill up the database with useful mocks, and that makes it easier to do many things.

Ruby tests are really important, in order for any piece of work to get merged to the OpenSupports codebase, all ruby tests need to pass, so you run them at the start of setting up your development environment, and just after you add/change any piece of functionality, so that you know that everything is working fine.

**Ruby tests**
1. Get rid of ruby (I don't think is necessary, but if you can do it, great)
2. Install `rbenv` (this is a manager of ruby versions, we need an older version to run the tests)
3. Using `rbenv`, install a version older or equal to `2.3.0`, I'm personally using exactly `2.3.0` right now.
4. Go to `opensupports/tests`
5. Install the gems: `gem install mysql bacon mechanize mailfactory mail`

After all those steps are done, you usually run the ruby tests by running `make run` inside the `opensupports/tests/` folder.

---------------

The username and password of the main staff user for the development environment are `staff@opensupports.com`/`staff`.

The idea is that you create a fork of OpenSupports, you create your own branches and start doing your changes there, and when the branch is in a ready state, you create a pull request to the main project, and then you can add @ivandiazwm, @guillegiu and/or me as reviewers, so we can check out what did you do, and if it is safe to merge.

Hope this helps, and thanks for your enthusiasm!
