### ISSUE TITLE
Can’t add department with cyrillic names.

### ISSUE THREAD

**Issue by userishere** [opensupports/opensupports#83]
When I try to add any department with cyrillic names nothing happens. No error is shown. I have to add departments in the database.

Btw, when I try to add api and use cyrillic names same issue happens.

**Comment by ivandiazwm** [comment]
This issues is caused because we are [validating it to be alphanumeric](https://github.com/opensupports/opensupports/blob/master/server/controllers/system/add-department.php#L34). It was put there for security reasons.

However, this need to fixed. We either change the validation or add all characters form other languages to the validation. 

I'm adding this to the bug fixing kanban,
Thanks for noticing this.

**Comment by ivandiazwm** [comment]
Fixed

**Comment by guillegiu** [comment]
Fixed
