### ISSUE TITLE
SMTP Problem

### ISSUE THREAD

**Issue by Paurek** [opensupports/opensupports#976]
Hello, when installing opensupport I wanted the email address but I have an infinite load and no errors, what should I do?

![image](https://user-images.githubusercontent.com/22663628/107635675-d2457580-6c6b-11eb-8f48-a3cde1bfb7a9.png)

**Comment by JustCodeIt4Head** [comment]
Hi,
is the abcdnutrition.com E-Mail Address a linked G-Suite Address? Since you are using G-Mails SMTP Server and try to authenticate with your E-Mail Address.
If your E-Mail Address (support@abcdnutrition.com) is NOT a G-Suite Business Account E-Mail, please use the SMTP Server of your own Mail Server for the Domain abcdnutrition.com.

Or is abcdnutrition.com just a "Test Value"?. In this Case, just Fill out the "Objet" and "Adresse du serveur de messagerie" and leave all the other Fields blank (if you already saved Values just empty them and click save).

**Comment by Paurek** [comment]
I found the problem thanks
